development:
  adapter: mysql
  database: unisbs_dev
  username: root
  password:

test:
  adapter: mysql
  database: unisbs_test
  username: root
  password:

production:
  adapter: mysql
  database: unisbs
  username: root
  password:
